splunk/addonfactory-ucc-library

splunktaucclib/splunk_aoblib/setup_util.py

Update get_schema_path in setup_util of splunk_aoblib
To resolve below error:

Update get_schema_path in setup_util of splunk_aoblib

---

splunktaucclib/rest_handler/util.py

-Added following functions in `splunktaucclib\rest_handler\util.py` from previous version of library.
1. makeConfItem
2. getBaseAppName
following internal files are expecting this functions there: 
```
splunktaucclib\rest_handler\base.py
splunktaucclib\rest_handler\datainput.py
splunktaucclib\rest_handler\cred_mgmt.py
```
[jira link](https://jira.splunk.com/browse/ADDON-30711)

ADDON-30711: Added missing functions in rest_handler\util.py

---

splunktaucclib/alert_actions_base.py

Fixed issue reading alert action results by changing gzip mode to "rt" (text) instead of "rb" (binary).

fix(alert_actions_base.py): open alert results as text instead of binary

---

poetry.lock
pyproject.toml

Updating splunktalib after releasing fixes: https://github.com/splunk/addonfactory-ta-library-python/pull/6 and https://github.com/splunk/addonfactory-ta-library-python/pull/7.

feat: update splunktalib to 1.2.1

---

splunktaucclib/rest_handler/endpoint/validator.py

I am referring to the latest semgrep failures from #45.
Those failures were false positive. I moved the `check` functions outside of `__init__` method.

fix: semgrep issues

---

splunktaucclib/rest_handler/endpoint/validator.py

**Issue:** If in `restmap.conf` rest handler is set to be persistent (which is the default in UCC rest handlers) then the list of messages will keep on increasing and fill up memory until the rest handler gets refreshed.
**Note:** Even with persistent handlers, this can only cause issue if the user requests the endpoint continuously.
**Fix:** Limit the length of the validation message list

fix: limit the size of validation message queue

---

poetry.lock
pyproject.toml
splunktaucclib/alert_actions_base.py
splunktaucclib/config.py
splunktaucclib/rest_handler/base.py
splunktaucclib/rest_handler/poster.py
splunktaucclib/rest_handler/teardown.py
splunktaucclib/rest_handler/util.py

Changes:
- feat: migration from httplib2 to requests library
- BREAKING CHANGE: the 'build_http_connection function of alert_actions_base.py has been deprecated. Users can use 'send_http_request' function of the same class or use 'requests.request' function.

feat: migration from httplib2 to requests library

---

.github/workflows/build-test-release.yml

From `poetry` [README](https://github.com/python-poetry/poetry#installation):
Warning: The previous get-poetry.py installer is now deprecated, if you are currently using it you should migrate to the new, supported, install-poetry.py installer.

ci: update poetry installation commands

---

splunktaucclib/data_collection/ta_data_collector.py

There is a bug when you are trying to ingest `[{"Data": "Sample1"}, {"Data": "Sample2"}]`
it becomes `[{"Data": "Sample1"}, {"Data": "Sample2"}%5D` in Splunk because of the
`splunktalib`'s `escape_cdata` function used.
This PR removes usage of this function and uses `defusedxml.sax.saxutils.escape` function to escape
all the characters before sending to Splunk.
P.S. You can play with it using this repository:
https://github.com/artemrys/splunk-xml-streaming-minimal-example.

fix: ingestion for XML streaming mode

---

splunktaucclib/data_collection/ta_mod_input.py

This fix was tested to work on Noah and Classic architectures.
Similar situation (in 2016...): https://community.splunk.com/t5/All-Apps-and-Add-ons/Splunk-Add-on-for-Tenable-Why-is-the-add-on-not-able-to/m-p/230462

fix: data collection on SHC

---

poetry.lock
pyproject.toml
splunktaucclib/rest_handler/credentials.py

Similar to https://github.com/splunk/addonfactory-solutions-library-python/pull/189.
This change should fix the situation when you try to get a specific password for you add-on
and some other password in other add-on is corrupted, then the configuration page is
not loading for all the add-ons.
**This fix requires solnlib to be at least 4.7.0 version.**

fix: look for the passwords in the particular realm, not all the passwords

---

.github/workflows/build-test-release.yml

The semgrep is failing because of some `hashlib` library usage which is not related to the fix that is being proposed. This needs to be investigated later.

ci: temporary disable semgrep for release

---

poetry.lock
pyproject.toml

Release a fix for https://github.com/splunk/addonfactory-ucc-library/security/dependabot/5

fix: require requests 2.31.0 and urllib3 < 2

---

poetry.lock
pyproject.toml

This PR introduces less constraints for some of the dependencies used in this library so consumers can benefit from widen ranges.

chore: relax dependency versions

---

.github/workflows/build-test-release.yml
tests/integration/demo/package/default/inputs.conf
tests/integration/test_rest_handler_handler.py

extending integration tests to include status cases 400 and 403

test: add integration tests

---

.github/workflows/build-test-release.yml
poetry.lock
splunktaucclib/rest_handler/handler.py
tests/integration/test_rest_handler_handler.py
tests/unit/test_rest_handler_error.py

* changing the content of error messages to make them more user-friendly.
* hide "You user do not have permission..." (https://splunk.atlassian.net/browse/ADDON-67423)

feat: simplifying error messages from core

---

splunktaucclib/splunk_aoblib/setup_util.py

Every time the `get_proxy_settings` function is called it's not necessary to log about it, that should be up to the caller unless in debug mode.

fix: reducing log level for every request

---

.github/workflows/build-test-release.yml
poetry.lock
pyproject.toml
splunktaucclib/common/log.py

support for solnlib library which was recently released with version v5.0.0
fix ci:
*removed cache poetry
*removed pipx installer
*change step order - `actions/setup-python@v5` before installing poetry

fix: add support for solnlib v5.x.x

---

splunktaucclib/data_collection/ta_data_client.py
splunktaucclib/data_collection/ta_data_collector.py
splunktaucclib/data_collection/ta_data_loader.py
splunktaucclib/data_collection/ta_mod_input.py

This PR is a potential fix for Segmentation Faults in Python 3.9 (more info here https://splunk.atlassian.net/browse/ADDON-71136). 
We found out that disabling stdout buffer implemented in `splunktalib` doesn't work for Python 3.8 & 3.9 (for 3.7 and >3.10 it works). The problem is with [this line](https://github.com/splunk/addonfactory-ta-library-python/blob/main/splunktalib/common/util.py#L142) (it every Python code, not only our TAs):
```
sys.stdout = os.fdopen(sys.stdout.fileno(), "wb", 0)
```
This problem affects everyone who uses `splunktaucclib`'s framework for modinputs.
As a solution, we removed disabling buffer and decided to flush immediately (as `ClassicEventWriter` from `solnlib` does).

fix: remove buffer disabling

---

.github/workflows/build-test-release.yml
splunktaucclib/rest_handler/endpoint/__init__.py
splunktaucclib/rest_handler/endpoint/field.py
splunktaucclib/rest_handler/handler.py
tests/integration/demo/globalConfig.json
tests/integration/demo/package/bin/demo_rh_demo.py
tests/integration/demo/package/bin/demo_rh_settings.py
tests/integration/test_rest_handler_handler.py

**Issue number:[ADDON-74237](https://splunk.atlassian.net/browse/ADDON-74237)**
Added support for default and custom name field validation
* RestModel now has an additional parameter "special_fields"
* RestEndpoint now has two additional methods for executing custom validations
* _pre_request decorator has new method "basic_name_validation" for basic validations
Name field will be validated on the server side
If your change doesn't seem to apply, please leave them unchecked.

feat: add default and custom validations for name field

---

.github/workflows/build-test-release.yml
pyproject.toml
splunktaucclib/__init__.py
splunktaucclib/rest_handler/endpoint/__init__.py
splunktaucclib/rest_handler/endpoint/field.py
splunktaucclib/rest_handler/handler.py
tests/integration/demo/globalConfig.json
tests/integration/demo/package/bin/demo_rh_demo.py
tests/integration/demo/package/bin/demo_rh_settings.py
tests/integration/test_rest_handler_handler.py

chore: merge develop into main

---

splunktaucclib/rest_handler/endpoint/__init__.py

This PR adds possibility to set need_reload flags in model constructors.

feat: add need_reload flags to model constructors

---

splunktaucclib/cim_actions.py

[Issue-323](https://github.com/splunk/addonfactory-ucc-library/issues/323)
Imported `codecs` module for the addinfo method of ModularAction in `cim_actions.py` file.

fix: import codecs

---

poetry.lock
pyproject.toml

Jira: https://splunk.atlassian.net/browse/ADDON-77054
This PR makes sure that `splunktaucclib` will require at least `2.0.2` version of `splunk-sdk`.

fix: require splunk-sdk at least 2.0.2

---

poetry.lock
pyproject.toml

This PR allows to install both `splunktaucclib` and `solnlib` in the same env.

fix: allow solnlib from 5.0.0

---

poetry.lock
pyproject.toml
splunktaucclib/rest_handler/endpoint/__init__.py
splunktaucclib/rest_handler/handler.py
tests/integration/demo/additional_packaging.py
tests/integration/demo/package/bin/demo_rh_test_reload_override.py
tests/integration/test_rest_handler_handler.py
tests/unit/conftest.py
tests/unit/fake_module.py
tests/unit/test_admin_external.py

This change allows to enable or disable config file reloads in TA's.
This option is stored in `_TA_config.conf`.
Example content:
```
[config]
need_reload = 0
```
This example indicates, that we override default `need_reload` values to 0 (false).
Example usage:
POST call to:
`/servicesNS/-/APP_NAME/conf-_TA-config`
with parameters:
- `name`=`config`
- `need_reload`=`0`
or, if it already exists, an update (also POST) call to:
`/servicesNS/-/APP_NAME/conf-_TA-config/config`
with parameters:
- `need_reload`=`0`

feat: allow enabling and disabling of reloads

---

tests/integration/test_rest_handler_handler.py

**Issue number:** [ADDON-78485](https://splunk.atlassian.net/browse/ADDON-78485)
**What kind of change does this PR introduce?**
Add test for basic CRUD operation for RestHandler.
No impact.
If an item doesn't apply to your changes, leave it unchecked.
See [the testing doc](https://splunk.github.io/addonfactory-ucc-generator/contributing/#build-and-test).

test: add basic integration test for CRUD

---

splunktaucclib/alert_actions_base.py
tests/unit/test_alert_actions_base.py

**Issue number:** [ADDON-82402](https://splunk.atlassian.net/browse/ADDON-82402)
**What kind of change does this PR introduce?**
Sometimes in alert actions empty "rid" parameter is send and it caused problems because it wasn't set but InvalidKey was returned.
Handlers for empty string was added.
If an item doesn't apply to your changes, leave it unchecked.
See [the testing doc](https://splunk.github.io/addonfactory-ucc-generator/contributing/#build-and-test).
**Demo/meeting:**
*Reviewers are encouraged to request meetings or demos if any part of the change is unclear*

fix: num if empty string
